name: cygdrop-github-actions-test

on: [push]

jobs:
  windows:
    runs-on: windows-2019
    env:
      REPOSITORY_DIR: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.REPOSITORY_DIR }}
        shell: msys2 {0}
    strategy:
      fail-fast: false
    name: Windows Server 2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: autoconf automake make sed zlib-devel
      - name: Install dependencies
        run: >
          pacman --noconfirm --needed -Sy
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-make
          mingw-w64-x86_64-nsis
          mingw-w64-x86_64-pango
          mingw-w64-x86_64-pkg-config
          cygutils
      - name: Run tests
        run: |
          export PATH=`cygpath -m '${{ env.PKG_PC_FILES_DIR }}'`
          sh ./scripts/demo.sh "$PATH"
        env:
          DISPLAY: ':99.0'
          RUN_WITH: cygdrop -p Backup -p Restore
          PKG_PC_FILES_DIR: ${{ env.REPOSITORY_DIR }}/.pkgconfig-pc-files
