name: cygdrop-github-actions-test

on: [push]

jobs:
  windows:
    runs-on: windows-2019
    env:
      REPOSITORY_DIR: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.REPOSITORY_DIR }}
        shell: msys2 {0}
    strategy:
      fail-fast: false
    name: Windows Server 2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: cygutils
      - name: Run tests
        run: |
          export PATH=`cygpath -m "${{ env.PKG_PC_FILES_DIR }}"`
          echo $PATH
        env:
          DISPLAY: ':99.0'
          RUN_WITH: cygdrop -p Backup -p Restore
          PKG_PC_FILES_DIR: ${{ env.REPOSITORY_DIR }}/.pkgconfig-pc-files
