name: cygdrop-github-actions-test

on: [push]

jobs:
  windows:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
        shell: msys2 {0}
    strategy:
      fail-fast: false
    name: Windows Server 2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: cygutils
      - name: Run tests
        run: |
          export DEMO=`cygpath --absolute "~/.pkgconfig-pc-files"`
          sh ./scripts/demo.sh "$DEMO"
        env:
          DISPLAY: ':99.0'
          RUN_WITH: cygdrop -p Backup -p Restore
